version: "3.8"

services:
  php:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www/html/
  db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: exam_task
            MYSQL_USER: root
            MYSQL_PASSWORD: example
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - sqlData:/var/lib/mysql

  adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080


volumes:
      sqlData: